### ISSUE TITLE
’IFDriver’ object has no attribute ’loaded_character’

### ISSUE THREAD

**Issue by badgids** [neph1/LlamaTale#4]
I can't seem to get t to createa new character or load a character. It gives this error everytime. Koboldcpp is working, and running on port 5001, however it doesn't seem as if anything is being passed to it. Any advice?

----

Do you want to load a saved game (’n’ will start a new game)? n

  * internal error (please report this):

  ——————————————————-
   CRASH OCCURRED! TIMESTAMP: 2023-08-09 09:19:00.243085
  ——————————————————-
   EXCEPTION: AttributeError
   MESSAGE: ’IFDriver’ object has no attribute ’loaded_character’
   Extended stacktrace follows (most recent call last):
     —-

  File “C:\Users\Badgids\AI\LlamaTale\tale\driver_if.py”, line 271, in IFDriver.main_loop
  Source code:
      self._continue_dialog(conn, dialog, response)

     —-

  File “C:\Users\Badgids\AI\LlamaTale\tale\driver.py”, line 378, in IFDriver._continue_dialog
  Source code:
      why, what = dialog.send(message or None)

  Local values:
      conn = <tale.player.PlayerConnection object at 0x000001AA5D984790>
      dialog = <generator object IFDriver._login_dialog_if at 0x000001AA5E584E40>
      message = False
      self = <tale.driver_if.IFDriver object at 0x000001AA5D893AC0>
     —-

  File “C:\Users\Badgids\AI\LlamaTale\tale\driver_if.py”, line 163, in IFDriver._login_dialog_if
  Source code:
      if self.loaded_character:

  Local values:
      conn = <tale.player.PlayerConnection object at 0x000001AA5D984790>
      load_saved_game = None
      self = <tale.driver_if.IFDriver object at 0x000001AA5D893AC0>

   EXCEPTION HERE: AttributeError: ’IFDriver’ object has no attribute ’loaded_character’
  ——————————————————-

  Please report this problem.

**Comment by neph1** [comment]
Hmm. I haven't encountered any login dialogs during my testing. What command do you run it with?

**Comment by badgids** [comment]
> Hmm. I haven't encountered any login dialogs during my testing. What command do you run it with?

The suggested: "python -m stories.prancingllama.story"

**Comment by badgids** [comment]
> I've added some error handling if character isn't loaded, please check out master or v0.7.3. Hopefully the game should load now.

Works as expected now. Great work and a quick fix! Thank you!
