### ISSUE TITLE
oobabooga text gen api support?

### ISSUE THREAD

**Issue by Jake36921** [neph1/LlamaTale#49]
CRASH OCCURRED! TIMESTAMP: 2023-11-16 18:31:49.883781
——————————————————-
 EXCEPTION: JSONDecodeError
 MESSAGE: Expecting value: line 1 column 1 (char 0)
 Extended stacktrace follows (most recent call last):
   —-

File “E:\etc\LlamaTale\tale\driver_if.py”, line 284, in IFDriver.main_loop
Source code:
    self._continue_dialog(conn, dialog, response)

   —-

File “E:\etc\LlamaTale\tale\driver.py”, line 385, in IFDriver._continue_dialog
Source code:
    why, what = dialog.send(message or None)

Local values:
    conn = <tale.player.PlayerConnection object at 0x00000191F989EAC0>
    dialog = <generator object IFDriver._login_dialog_if at 0x00000191F9A7E9E0>
    message = ’y’
    self = <tale.driver_if.IFDriver object at 0x00000191F9817790>
   —-

File “E:\etc\LlamaTale\tale\driver_if.py”, line 224, in IFDriver._login_dialog_if
Source code:
    player.look(short=False)  # force a ’look’ command to get our bearings

Local values:
    builder = <tale.charbuilder.IFCharacterBuilder object at 0x00000191F9B09A60>
    conn = <tale.player.PlayerConnection object at 0x00000191F989EAC0>
    load_saved_game = False
    loaded_player = None
    name_info = <tale.charbuilder.PlayerNaming object at 0x00000191F9B09D00>
    player = <Player 'tes' #54 @ 0x191f989ed60, privs:->
    prompt = ’’
    result = True
    self = <tale.driver_if.IFDriver object at 0x00000191F9817790>
    start_location = None
   —-

File “E:\etc\LlamaTale\tale\player.py”, line 121, in Player.look
Source code:
    self.tell(look_text, end=True, evoke=evoke)

Local values:
    evoke = True
    look_paragraphs = [’[Entrance]’, ’A room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.’, “There’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reac   …(truncated to 250)
    look_text = “[Entrance]\nA room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.\nThere’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reaches y   …(truncated to 250)
    self = <Player 'tes' #54 @ 0x191f989ed60, privs:->
    short = False
   —-

File “E:\etc\LlamaTale\tale\player.py”, line 81, in Player.tell
Source code:
    msg, rolling_prompt = mud_context.driver.llm_util.evoke(self._output,

Local values:
    __class__ = <class 'tale.player.Player'>
    alt_prompt = ’’
    end = True
    evoke = True
    format = True
    message = “[Entrance]\nA room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.\nThere’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reaches y   …(truncated to 250)
    self = <Player 'tes' #54 @ 0x191f989ed60, privs:->
    short_len = False
   —-

File “E:\etc\LlamaTale\tale\llm\llm_utils.py”, line 79, in LlmUtil.evoke
Source code:
    text = self.io_util.synchronous_request(request_body, prompt=prompt)

Local values:
    alt_prompt = ’’
    amount = 25
    cached_look = ’’
    message = “[Entrance]\nA room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.\nThere’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reaches y   …(truncated to 250)
    output_template = ’Original:[ {message}] Generated:{text}’
    player_io = <tale.player_utils.TextBuffer object at 0x00000191F98D7040>
    prompt = “Below is an instruction that describes a task, paired with an input that provides further context. As an game keeper for an RPG, write a response that appropriately completes the request.[Story context: The final outpost high up in a cold, craggy mo   …(truncated to 250)
    request_body = {’stop_sequence’: ’\n\n\n’, ’max_length’: 750, ’max_context_length’: 4096, ’temperature’: 1.0, ’top_k’: 120, ’top_a’: 0.0, ’top_p’: 0.85, ’typical_p’: 1.0, ’tfs’: 1.0, ’rep_pen’: 1.2, ’rep_pen_range’: 256, ’sampler_order’: [6, 0, 1, 3, 4, 2, 5], ’see   …(truncated to 250)
    rolling_prompt = “[Entrance]\nA room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.\nThere’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reaches y   …(truncated to 250)
    self = <tale.llm.llm_utils.LlmUtil object at 0x00000191F9817580>
    short_len = False
    skip_history = True
    text_hash_value = -2607203395444595668
    trimmed_message = “[Entrance]\nA room full of furry and snow-covered coats. Loud voices and roars of laughter can be heard from the main hall.\nThere’s a warm glow and loud, noisy conversations coming through a doorway to the north A biting wind reaches y   …(truncated to 250)
   —-

File “E:\etc\LlamaTale\tale\llm\llm_io.py”, line 38, in IoUtil.synchronous_request
Source code:
    parsed_response = self._parse_kobold_result(response.text)

Local values:
    prompt = “Below is an instruction that describes a task, paired with an input that provides further context. As an game keeper for an RPG, write a response that appropriately completes the request.[Story context: The final outpost high up in a cold, craggy mo   …(truncated to 250)
    request_body = {’stop_sequence’: ’\n\n\n’, ’max_length’: 750, ’max_context_length’: 4096, ’temperature’: 1.0, ’top_k’: 120, ’top_a’: 0.0, ’top_p’: 0.85, ’typical_p’: 1.0, ’tfs’: 1.0, ’rep_pen’: 1.2, ’rep_pen_range’: 256, ’sampler_order’: [6, 0, 1, 3, 4, 2, 5], ’see   …(truncated to 250)
    response = <Response [404]>
    self = <tale.llm.llm_io.IoUtil object at 0x00000191F9834DF0>
   —-

File “E:\etc\LlamaTale\tale\llm\llm_io.py”, line 87, in IoUtil._parse_kobold_result
Source code:
    return json.loads(result)[’results’][0][’text’]

Local values:
    result = ’<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"\n        "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n    <head>\n        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">\n        <title>Error response</title>\n    </head>\n   …(truncated to 250)
    self = <tale.llm.llm_io.IoUtil object at 0x00000191F9834DF0>
   —-

File “E:\etc\Anaconda\lib\json\__init__.py”, line 346, in loads
Source code:
    return _default_decoder.decode(s)

Local values:
    cls = None
    kw = {}
    object_hook = None
    object_pairs_hook = None
    parse_constant = None
    parse_float = None
    parse_int = None
    s = ’<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"\n        "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n    <head>\n        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">\n        <title>Error response</title>\n    </head>\n   …(truncated to 250)
   —-

File “E:\etc\Anaconda\lib\json\decoder.py”, line 337, in JSONDecoder.decode
Source code:
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

Local values:
    _w = <built-in method match of re.Pattern object at 0x00000191F708D9F0>
    s = ’<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"\n        "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n    <head>\n        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">\n        <title>Error response</title>\n    </head>\n   …(truncated to 250)
    self = <json.decoder.JSONDecoder object at 0x00000191F709BB80>
   —-

File “E:\etc\Anaconda\lib\json\decoder.py”, line 355, in JSONDecoder.raw_decode
Source code:
    raise JSONDecodeError(“Expecting value”, s, err.value) from None

Local values:
    idx = 0
    s = ’<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"\n        "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n    <head>\n        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">\n        <title>Error response</title>\n    </head>\n   …(truncated to 250)
    self = <json.decoder.JSONDecoder object at 0x00000191F709BB80>

 EXCEPTION HERE: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Jake36921** [comment]
nvm I forgot to change the backend to "openai" in llm_config💀

**Comment by neph1** [comment]
I might change that to default, considering most people probably use an openai compatible backend.
